### ISSUE TITLE
Compiled Failed

### ISSUE THREAD

**Issue by yuankunluo** [somq/ionicv4-ngrx-remote-devtool#1]
` 
error TS2416: Property 'connect' in type
'RemoteDevToolsProxy' is not assignable to the same property in base type 'ReduxDevtoolsExtension'.
[ng]   Type '(options: { shouldStringify?: boolean; instanceId: string; }) => ReduxDevtoolsExtensionConnection' is not assignable to type '(options: ReduxDevtoolsExtensionConfig) => ReduxDevtoolsExtensionConnection'.
[ng]     Types of parameters 'options' and 'options' are incompatible.
[ng]       Type 'ReduxDevtoolsExtensionConfig' is not assignable to type '{ shouldStringify?: boolean; instanceId: string; }'.
[ng]         Property 'instanceId' is missing in type 'ReduxDevtoolsExtensionConfig'.
[ng] 
`

The interface is incompatible.

i am using ionic 4

**Comment by sertal70** [comment]
In `ngrx-devtool-hack.ts` try replacing the original `connect()` with this:

```Typescript
connect(options: ReduxDevtoolsExtensionConfig): ReduxDevtoolsExtensionConnection {
    const connectOptions = Object.assign(this.defaultOptions, options);

    this.remotedev = connect(connectOptions);

    const connectionProxy = new RemoteDevToolsConnectionProxy(
      this.remotedev,
      connectOptions.name
    );
    return connectionProxy;
  }
```

It worked for me.

**Comment by JuanCruzGasparro** [comment]
> In `ngrx-devtool-hack.ts` try replacing the original `connect()` with this:
> 
> ```ts
> connect(options: ReduxDevtoolsExtensionConfig): ReduxDevtoolsExtensionConnection {
>     const connectOptions = Object.assign(this.defaultOptions, options);
> 
>     this.remotedev = connect(connectOptions);
> 
>     const connectionProxy = new RemoteDevToolsConnectionProxy(
>       this.remotedev,
>       connectOptions.name
>     );
>     return connectionProxy;
>   }
> ```
> 
> It worked for me.

Fine here!
